targets:
  $default:
    builders:
      build_web_compilers|entrypoint:
        options:
          dart2js_args:
            - -O4
            - --no-source-maps
            - --fast-startup
            - --trust-primitives 