// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyC2MJAKJTTFAEBC0_B5e0JXoOsHfMhomNk",
    authDomain: "trakr-def.firebaseapp.com",
    databaseURL: "https://trakr-def-default-rtdb.firebaseio.com",
    projectId: "trakr-def",
    storageBucket: "trakr-def.firebasestorage.app",
    messagingSenderId: "983795207283",
    appId: "1:983795207283:web:46d6e8400ae791eab62e06"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFkTr64wmo7DQxDRK7lPnG5Qe12mO9r5o',
    appId: '1:983795207283:android:39fab263e4c23a57b62e06',
    messagingSenderId: '983795207283',
    projectId: 'trakr-def',
    storageBucket: 'trakr-def.firebasestorage.app',
  );
}
